Improve error handling
arthaud/git-dumper pull request #13
Opened 2020-11-15 05:45 UTC by DashLt

I added an exception handler to Worker.run so a single failed task doesn't crash the whole worker, and also added logic to check for HTML responses (error pages that give a 200 response code instead of 404) and zero-length responses (I've run into them, surprisingly).

2020-11-15 22:03 UTC, arthaud requested changes
That looks pretty good, thanks for working on this. Please address my feedback and I will happily merge this :)

2020-11-15 22:03 UTC, arthaud commented on git-dumper.py
> +    return "html" in response.headers["Content-Type"]
Should it be `text/html`?

2020-11-15 22:03 UTC, arthaud commented on git-dumper.py
> +            except Exception as e:
We don't need `e` here, we could just `except:`?

2020-11-15 22:03 UTC, arthaud commented on git-dumper.py
> +                return []
Here and below: Instead of using verification[0] and verification[1] we could use unpacking:
```
valid, error_message = verify_response(response)
if not valid:
    printf(error_message, url, filepath)
    return []

2020-11-15 22:03 UTC, arthaud commented on git-dumper.py
> -        printf('error: %s/.git/HEAD is not a git HEAD file\n', url, file=sys.stderr)
Could we keep this check?

2020-11-15 22:03 UTC, arthaud commented on git-dumper.py
> +
nitpick: remove the empty newline

2020-11-16 19:19 UTC, DashLt commented on git-dumper.py
> +    return "html" in response.headers["Content-Type"]
You're right, good catch.

2020-11-16 19:22 UTC, DashLt commented on git-dumper.py
> +            except Exception as e:
Oh, you're right, good catch

2020-11-23 18:07 UTC, arthaud commented
Could you please apply my suggested changes and update the pull request?

2021-02-21 05:40 UTC, JHHAX commented
I would love if this could be approved, this is an amazing change

2021-02-21 21:55 UTC, arthaud commented
Since the author wouldn't apply my suggested changed, I did that myself. Thanks for the contribution!

2021-02-21 21:55 UTC, closed without merging