Added ability to resume stalled/cancellled sessions
arthaud/git-dumper pull request #14
Opened 2020-11-28 17:39 UTC by AdamWelch1

- Added logic: If a file already exists, don't re-download the file in most cases. Prints 'Already downloaded' in place of 'Fetching' message.

This allows resuming a stalled or cancelled session.

2020-11-30 03:11 UTC, arthaud requested changes
Hi @AdamWelch1, thanks for working on this!

This looks awesome. I have made a few suggestions on it. Please address the feedback and I will merge this happily :)

2020-11-30 03:11 UTC, arthaud commented on git-dumper.py
> +
nitpick: please remove the extra whiteline

2020-11-30 03:11 UTC, arthaud commented on git-dumper.py
> +
ditto

2020-11-30 03:11 UTC, arthaud commented on git-dumper.py
> +        if not os.path.isfile(filepath):
We can use a if/else
```suggestion
        if os.path.isfile(filepath):
            printf('[-] Already downloaded %s/%s\n', url, filepath)
        else:
```

2020-11-30 03:11 UTC, arthaud commented on git-dumper.py
> +    # assert not os.listdir(directory), '%s is not empty' % directory
Maybe we could print a warning instead if the directory is not empty?

2020-11-30 03:11 UTC, arthaud commented on git-dumper.py
> +        # parser.error('%s is not empty' % args.directory)
Please remove this instead of letting commented code in the repo

2020-12-02 05:47 UTC, AdamWelch1 commented
Hey @arthaud I'm glad you like my modifications ^_^
I've made the changes that you suggested. I'm not familiar with Python, so I hope the code isn't too sloppy!

Thanks for making this awesome tool and sharing it. You rock ;)

2020-12-02 06:38 UTC, arthaud commented
Thanks for updating the PR :)

2020-12-02 06:38 UTC, merged